---
kind: pipeline
type: docker
name: test-and-lint

steps:
  - name: lint
    image: golangci/golangci-lint:latest
    environment:
      CGO_ENABLED: "0"
    commands:
      - golangci-lint run

  - name: test-1.14
    image: golang:1.14.4-alpine
    environment:
      CGO_ENABLED: "0"
    commands:
      - go test -cover -test.v .

  - name: test-1.13
    image: golang:1.13.12-alpine
    environment:
      CGO_ENABLED: "0"
    commands:
      - go test -cover -test.v .

