---
kind: pipeline
type: docker
name: test-and-lint

steps:
  - name: lint
    image: code.pztrn.name/containers/mirror/golangci/golangci-lint:v1.46.2
    environment:
      CGO_ENABLED: "0"
    commands:
      - golangci-lint run

  - name: test-1.18
    image: code.pztrn.name/containers/mirror/golang:1.18.3-alpine
    environment:
      CGO_ENABLED: "0"
    commands:
      - go test -cover -test.v .
